config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'books#top'
  get '/about' => 'books#about'
  get '/edit' => 'books#edit'
  resources :users
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	validates :title, presence: true, length: { maximum: 50 }
    validates :opinion, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,authentication_keys: [:name]

         has_many :books, dependent: :destroy

         attachment :image


	validates :name, presence: true, length: { minimum: 2,maximum: 20 }
    validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
  	user_path(current_user)
  end

  # def after_sign_out_path_for(resource)
  #   new_user_session_path # ログアウト後に遷移するpathを設定
  # end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name,:password])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	  before_action :authenticate_user!, except:[:top,:about]

	def top
	end

	def about
	end

	def new
		@book = Book.new
    end

    def create
    	@book = Book.new(book_params)
    	@book.user_id = current_user.id
    	if @book.save
  		   flash[:notice] = "Book was successfully created"
  		   redirect_to book_path(@book)
  		else
 		   @books = Book.all
  		   render :index
  		end
	end

    def index
	   	@book = Book.new
    	@books = Book.all
    end

    def show
		  @bookn = Book.new
    	@book = Book.find(params[:id])
    end

    def edit
    	@book = Book.find(params[:id])
      if @book.user_id != current_user.id
        redirect_to book_path(@book)
      end
    end

    def update
  		@book = Book.find(params[:id])
	  	if  @book.update(book_params)
	  		flash[:notice] = "successfully"
	  		redirect_to book_path(@book)
	    else
	  		render :edit
	  	end
  	end

    def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
	end

    private
    def book_params
        params.require(:book).permit(:title, :opinion)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
  	@users = User.all
    @book = Book.new
  end

  def show
  	 @user = User.find(params[:id])
  	 @books = @user.books
	   @book = Book.new
  end

  def edit
  	  @user = User.find(params[:id])
  end

  def update
  	    @user = User.find(params[:id])
    if  @user.update(user_params)
    	  flash[:notice] = "successfully"
        redirect_to user_path(@user.id)
    else
	      render :edit
    end

  end


	  private
	  def user_params
	      params.require(:user).permit(:name, :image, :introduction)
	  end


  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_sidebar.html.erb
         <div class="col-lg-3">
            <%= flash[:notice] %>
            <%= flash[:alert] %>

            <h2>User info</h2>
            <%= attachment_image_tag @user, :image, :fill, 60, 60, fallback: "no_image.jpg",size: '60x60'%>
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <th>name</th>
                        <th><%= user.name %></th>
                    </tr>
                    <tr>
                        <th>introduction</th>
                        <th><%= user.introduction %></th>
                    </tr>
                </tbody>
            </table>


            <% if user.id == current_user.id %>
                    <p><%= link_to "", edit_user_path(user),class: 'edit_user_#{user.id} glyphicon glyphicon-wrench btn btn-default col-lg-12' %></p>
            <% end %>


            <%= form_for(book) do |f| %>

                <% if book.errors.any? %>
                    <%= book.errors.count %>error
                    <% book.errors.full_messages.each do |message| %>
                        <%= message %>
                    <% end %>
                <% end %>

                <h1>New book</h1>

                <h4>Title</h4>
                <%= f.text_field :title,class: "book_title" %>

                <h4>Opinion</h4>
                <%= f.text_area :opinion,class: "book_body" %>

                <p><%= f.submit "Create Book" %></p>

            <% end %>
        </div>

app/views/books/about.html.erb
<div class="container">
	<h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers!!</h1>
</div>

app/views/books/edit.html.erb
<div class="container">
      <div class="row">
      	<div class="col-md-3"></div>
			<div class="col-md-6">
				<h1>Editing Book</h1>
					<%= form_for(@book) do |f| %>

						<h4>Title</h4>

						<%= f.text_field :title ,class: "book_title"%>

						<h4>Opinion</h4>

						<%= f.text_area :opinion ,class: "book_body"%>

						<%= f.submit 'Update Book',class: "btn btn-default btn-block btn-primary book_#{@book.id}"%>
						<a><%= link_to 'Show', book_path,class: "book_#{@book.id}" %></a> |
						<a><%= link_to 'Back', books_path,class: "back" %></a>
					<% end %>
			</div>
			<div class="col-md-3"></div>
		</div>
</div>

app/views/books/index.html.erb
<div class="container">
      <div class="row">
       <%= render 'layouts/error_messages',book: @book %>
       <%= render 'books/sidebar', books: @books,user: current_user,book: @book %>
        <div class="col-lg-9">
          <h1>Books</h1>
            <table class="table table-striped">
                  <thead>
                    <tr>
                      <th></th><th>Title</th><th>Opinion</th><th></th><th></th>
                    </tr>
                  </thead>
                  <tbody>
                      <% @books.each do |book| %>
                      <tr>
                        <td><%= attachment_image_tag book.user, :image, :fill, 60, 60, fallback: "no_image.jpg", size: '60x60' %></td>
                        <td><%= link_to book_path(book.id),class: "book_#{book.id}" do %>
                        <%= book.title %>
                        <% end %></td>
                        <td><%= book.opinion %></td>
                       </tr>
                      <% end %>
                  </tbody>
            </table>
        </div>
      </div>
</div>

app/views/books/new.html.erb
<h2>User info</h2>
<img class="attachment user profile_image fallback" src="/assets/no_image-ede28af4bad96368ef41be1b4be1cffce0d9402540f75d17895e32cb0d2af5e6.jpg" alt="No image">
<table>
    <tbody>
        <tr>
            <th>name</th>
            <th></th>
        </tr>
        <tr>
            <th>introduction</th>
            <th></th>
        </tr>
    </tbody>
</table>
<div class="row"></div>





<%= form_for(@book) do |f| %>

    <% if @book.errors.any? %>
        <%= @book.errors.count %>error
        <% @book.errors.full_messages.each do |message| %>
            <%= message %>
        <% end %>
    <% end %>

    <h1>New book</h1>

    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Opinion</h4>
    <%= f.text_area :opinion %>

    <%= f.submit "Create Book" %>

<% end %>

app/views/books/show.html.erb
<div class="container">
      <div class="row">
        <%= render 'books/sidebar', books: @books, user: @book.user,book: @bookn %>
        <%= render 'layouts/error_messages',user: @book.user,book: @bookn %>
        <div class="col-lg-9">
          <h1>Book detail</h1>
          <table class="table table-striped">
                <thead>
                  <tr>
                    <th></th><th></th><th></th><th></th><th></th>
                  </tr>
                </thead>
                <tbody>
                    <tr>
                      <td><%= attachment_image_tag @book.user, :image, :fill, 60, 60, fallback: "no_image.jpg" ,size: '60x60' %>
                        <br><%= link_to @book.user.name, user_path(@book.user),class: "user_#{@book.user}" %>
                      </td>
                      <td><%= link_to book_path(@book.id),class: "book_#{@book.id}" do %><%= @book.title %><% end %></td>
                      <td><%= @book.opinion %></td>
                     <% if current_user.id == @book.user.id %>
                       <td class = "edit"><%= link_to 'Edit', edit_book_path(@book.id),class: "edit_book_#{@book.id}" %></td>
                       <td class = "destroy"><%= link_to 'Destroy', book_path(@book.id),class: "destroy_book_#{@book.id}" ,method: :delete %></td>
                     <% end %>
                     </tr>
                </tbody>
          </table>
          <% if flash[:notice] %>
            <div class = "flash">
            <%= flash[:notice] %>
            </div>
          <% end %>
        </div>
      </div>
</div>

app/views/books/top.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6">

			<h1>Welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers!!</h1>
			<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers,</p>

			<p>you can share and exchange your opinions , inpressions , and emotions</p>

			<p>about varioius books!</p>

			<div class="row">
				<%= link_to 'login', new_user_session_path,class: "sign_in btn btn-default btn-block btn-primary" %>
			</div>
			<div class="row">
				<%= link_to 'sign up', new_user_registration_path,class: "signout btn btn-default btn-block btn-success" %>
			</div>
		</div>
		<div class="col-md-3"></div>
	</div>

</div>

app/views/layouts/_error_messages.html.erb
<% if book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if user_signed_in? %>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"   data-toggle="collapse" data-target="#navbarEexample7">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <p class="navbar-brand">
            Bookers
            </p>
          </div>

          <div class="collapse navbar-collapse" id="navbarEexample7">
            <ul class="nav navbar-nav navbar-right">
              <li class="navbar-text"><%= link_to ' Home', user_path(current_user),class: 'home glyphicon glyphicon-home' %></li>

              <li class="navbar-text"> <%= link_to ' Users', users_path,class: "users glyphicon glyphicon-user"  %></li>
              <li class="navbar-text"> <%= link_to " Books", books_path,class: 'books glyphicon glyphicon-book' %></li>
              <li class="navbar-text"> <%= link_to " logout", destroy_user_session_path, method: :delete,class: 'logout glyphicon glyphicon-log-out' %>
              </li>
            </ul>
          </div>
        </div>
      </nav>

    <% else %>

      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"   data-toggle="collapse" data-target="#navbarEexample7">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <p class="navbar-brand">
            Bookers
            </p>
          </div>

          <div class="collapse navbar-collapse" id="navbarEexample7">
            <ul class="nav navbar-nav navbar-right">
              <li class="navbar-text"><%= link_to ' Home', root_path,class: 'home glyphicon glyphicon-home' %></li>

              <li class="navbar-text"> <%= link_to ' About', about_path,class: 'about glyphicon glyphicon-link'  %></li>
              <li class="navbar-text"> <%= link_to " sign up", new_user_registration_path,class: 'sign_up glyphicon glyphicon-edit' %></li>
              <li class="navbar-text"> <%= link_to " login", new_user_session_path,class: 'sign_in glyphicon glyphicon-log-in' %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/_sidebar.html.erb
         <div class="col-lg-3">
            <%= flash[:notice] %>
            <%= flash[:alert] %>

            <h2>User info</h2>
            <%= attachment_image_tag @user, :image, :fill, 60, 60, fallback: "no_image.jpg",size: '60x60'%>
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <th>name</th>
                        <th><%= user.name %></th>
                    </tr>
                    <tr>
                        <th>introduction</th>
                        <th><%= user.introduction %></th>
                    </tr>
                </tbody>
            </table>


            <% if @user.id == current_user.id %>
		            <%= link_to "", edit_user_path(@user),class: " edit_user_#{@user.id} glyphicon glyphicon-wrench btn btn-default col-lg-12" %>

            <% end %>



            <%= form_for(book) do |f| %>

                <% if book.errors.any? %>
                    <%= book.errors.count %>error
                    <% book.errors.full_messages.each do |message| %>
                        <%= message %>
                    <% end %>
                <% end %>

                <h1>New book</h1>

                <h4>Title</h4>
                <%= f.text_field :title,class: "book_title" %>

                <h4>Opinion</h4>
                <%= f.text_area :opinion,class: "book_body" %>

                <p><%= f.submit "Create Book" %></p>

            <% end %>
        </div>

app/views/users/edit.html.erb
<div class="container">
<% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
	<h2>User info</h2>
	<%= form_for(@user) do |f| %>
	        <label>Name</label>
	        <%= f.text_field :name,class: "name" %>

	        <%= attachment_image_tag @user, :image, :fill, 60, 60, fallback: "no_image.jpg",size: '60x60'%>

	        <h5>Image</h5>
	   		<%= f.attachment_field :image,class: "user_image", placeholder: "プロフィール画像" %>

	   		<label>Introduction</label>
	   		<%= f.text_area :introduction,class: "introduction" %>

	    	<p><%= f.submit "Update User" %></p>
	<% end %>
</div>

app/views/users/index.html.erb
<div class="container">
      <div class="row">
        <%= render 'books/sidebar', books: @books,user:current_user,book: @book %>
         <div class="col-lg-9">
            <h1>Users</h1>
                <table class="table table-striped">
                      <thead>
                        <tr>
                          <th>image</th><th>name</th><th></th>
                        </tr>
                      </thead>
                      <tbody>
                          <% @users.each do |user| %>
                           <tr>
                           	<td><%= attachment_image_tag user, :image, :fill, 60, 60, fallback: "no_image.jpg", size: '60x60' %></td>
                            <td><%= user.name %></td>
                            <td><%= link_to 'Show', user_path(user),class: "user_#{user.id}" %></td>
                           </tr>
                          <% end %>
                      </tbody>
                </table>
         </div>
      </div>
</div>

app/views/users/show.html.erb
<div class="container">
      <div class="row">
          <%= render 'sidebar', books: @books, book: @book,user: @user %>
        <div class="col-lg-9">
          <h1>Books</h1>
          <table class="table table-striped">
                <thead>
                  <tr>
                    <th></th><th>Title</th><th>Opinion</th>
                  </tr>
                </thead>
                <tbody>
                	  <% @books.each do |book| %>
                      <tr>
                        <td><%= attachment_image_tag book.user, :image, :fill, 60, 60, fallback: "no_image.jpg", size: '60x60' %></td>
                        <td><%= link_to book_path(book.id),class: "book_#{book.id}" do %><%= book.title %><% end %></td>
                        <td><%= book.opinion %></td>
                      </tr>
                	  <% end %>
                </tbody>
          </table>
        </div>
      </div>
</div>